### PR TITLE
Bypass GPU Check in settings menu

### PR DESCRIPTION
**Pull request by memedmusic**

### CODE REVIEW

**Comment by vtheskeleton** [comment]
Wasnt the gpu bypass called something different?

**Comment by memedmusic** [comment]
> Wasnt the gpu bypass called something different?

According to the !bypass command in discord it is bypassGPUChecks

**Comment by vtheskeleton** [comment]
So it seems, is this tested?

**Comment by memedmusic** [comment]
indeed

**Comment by vtheskeleton** [comment]
Well if this goes wrong blame mitch

**Pull request merged**
