### PR TITLE
Add hash check

### PR DESCRIPTION
**Pull request by TheBlueBurger**
~~This is not ready to be merged yet, it has not been tested and fileLocation, fileName and fileExtension arent defined yet. It also needs hashes to be added to miners.json, but it is a start.~~

This pr adds hashes to miners, not very tested

### CODE REVIEW

**Comment by Vukkyy** [comment]
:kaykay_owie:

**Comment by memedmusic** [comment]
I think its working now, but I'm gonna do some more testing first

**Comment by TheBlueBurger** [comment]
I'll test this when I come home

**Comment by walkxcode** [comment]
> This is not ready to be merged yet, it has not been tested and fileLocation, fileName and fileExtension arent defined yet. It also needs hashes to be added to miners.json, but it is a start.

Make this a WIP pull?

**Pull request closed without merging**
