### PR TITLE
Use saladbind's directory instead of "."

### PR DESCRIPTION
**Pull request by Username404-59**

### CODE REVIEW

**Comment by Username404-59** [comment]
I haven't tested this enough

**Comment by Username404-59** [comment]
mining.json does not work yet, i'll close this pull request in the meantime

**Comment by Vukkyy** [comment]
we can mark it as a draft

**Comment by Username404-59** [comment]
yeah I just didn't know how to do it

**Comment by Username404-59** [comment]
nevermind, miners.json does work, the issue was that I had the windows version of a xmrig installed (because I tested it with wine before) and saladbind was trying to use it instead of replacing it with the linux version

**Comment by Username404-59** [comment]
CodeQL is probably right, from their wiki:
["The shell command will, however, fail to work as intended if the absolute path of the script’s directory contains spaces"](https://codeql.github.com/codeql-query-help/javascript/js-shell-command-injection-from-environment/)

To fix this, an array is needed

**Comment by Username404-59** [comment]
This looks good to me!

The produced windows and linux executables work ( though I don't know if the macOS one does)

**Comment by Username404-59** [comment]
Note that I forgot to remove a `startMenuCheck` usage [here](https://github.com/LITdevs/SaladBind/blob/main/src/index.js#L9)

**Comment by vtheskeleton** [comment]
Thanks, I've removed it. As it shouldn't break anything currently I won't deploy another release.

**Pull request merged**
